### ISSUE TITLE
Unable to establish remote connection after upgrade to 1.0.15

### ISSUE THREAD

**Issue by neurofoo** [neo4j-apps/neo4j-desktop#10]
All settings the same as in the previous version. I create a ssh tunnel to my remote neo4j cluster. On attempting to connect I get an error:

```
Unable to establish remote connection: conflict: Document update conflict
```

I am able to connect to the remote cluster via Chrome (i.e., http://localhost:7474/browser)

**Comment by BarsaTM** [comment]
@neurofoo Thank you for a feedback!
Please let us know if the issue is still present.

**Comment by Metaur** [comment]
Reopen the issue, if it still is reproducible with latest Neo4j Desktop
