### ISSUE TITLE
Correct Graph App icon only shows up after reload

### ISSUE THREAD

**Issue by tholiebig** [neo4j-apps/neo4j-desktop#102]
When installing a new Graph App the Graph App sidebar list on the very left displays the default/standard Graph App icon (circled red in the shot below). The correct icon is not shown until reload of the Desktop UI or restart of Neo4j Desktop.

![Bildschirmfoto 2021-01-28 um 14 37 35](https://user-images.githubusercontent.com/5681368/106154966-73b6cc80-6180-11eb-9b61-8c96c93ae043.png)

**Comment by jk05** [comment]
Thanks for bringing this up @tholiebig. We have hopefully fixed this in the upcoming release. We can check then and close this if its no longer an issue.
