### ISSUE TITLE
Stuck in password entry dialog

### ISSUE THREAD

**Issue by neurofoo** [neo4j-apps/neo4j-desktop#11]
See image. Try to enter password. Password fails. Try to leave the dialog via click outside the dialog or pressing ESC, nothing.

<img width="999" alt="screen shot 2018-03-07 at 12 37 56 pm" src="https://user-images.githubusercontent.com/1616544/37108252-9a012318-2204-11e8-8268-41ac0279aab8.png">

**Comment by BarsaTM** [comment]
Thank you for a feedback! 
It will be fixed soon.

**Comment by BarsaTM** [comment]
Fixed in 1.1.8 release.
