### ISSUE TITLE
Database failed to create: Error: Could not change password

### ISSUE THREAD

**Issue by Jahanobik234** [neo4j-apps/neo4j-desktop#12]
I'm getting the above error when I attempt to create a new 3.3.3 database. No matter the password I try, this is failing. Any help in successfully creating the database would be welcomed!

![image](https://user-images.githubusercontent.com/16598917/37560498-9f9f6010-2a0f-11e8-9f40-07a37c48d258.png)

Thanks!

**Comment by oskarhane** [comment]
Thanks for the report!
What operating system are you on?

We recently released a new version, can you try with that?

**Comment by mamathadesireddy** [comment]
I am using Neo4j 1.0.19 and getting the same error when I try to create a local graph using Neo4j Desktop application.
**Error:Database failed to create: Error: Could not change password**

Can anyone aware of the solution for the above problem.

**Comment by Metaur** [comment]
Could you please share the app logs? Either in developer tools while the app is running, or in a log file, that is located at 'C:/Users/{username}/.Neo4jDesktop/log.log'

**Comment by LuchoTurtle** [comment]
I am having the exact same problem but with the 3.3.5 database version on Windows 10 (1709 version) and I'm using the 1.0.21 version of Neo4j. This has actually been bugging me for a while. I've reinstalled Neo4j several times and I have inclusively deleted all AppData files after each install just in case and this error just keeps popping up.

I've checked the log files and I found out this is the error that's mainly causing the issue: 
**[error] Neo4jAdmin: Error: Could not find or load main class '-XX:+UseG1GC'**

I know it seems pretty obvious but I've yet to find a solution successfully. I'm just writing here to add my two cents. I'm attaching the log files, in case y'all need it.

[log.log](https://github.com/neo4j-apps/neo4j-desktop/files/1920398/log.log)

Thanks!

**Comment by Metaur** [comment]
@LuchoTurtle Please try removing the `dbms.jvm.additional` entry from neo4j config and start again.

**Comment by Metaur** [comment]
@zhongqiujie Have you tried running `neo4j-admin.bat` script manually? 
Also, I've noted that your data path (`C:\Users\henry.Neo4jDesktop`) looks weird, how did you configure that?

**Comment by Sceurpien** [comment]
I had the same issue, and I wrote a simple article how you can manage to start Neo4j on a Win10 computer.

https://www.linkedin.com/pulse/how-kill-neo4j-soon-you-start-g%C3%A1bor-imre-bata-kov%C3%A1cs/

I hope it helps.

**Comment by Metaur** [comment]
@Sceurpien this issue has been fixed in the latest release. Now Desktop uses its own bundle jdk, which is 100% compatible with all neo4j versions available for download.

**Comment by Metaur** [comment]
Will close this issue, as the fix is available. Please reopen if needed
