### ISSUE TITLE
Desktop plugin installer doesn't allow other plugins to register with the server 

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-apps/neo4j-desktop#13]
There's an interesting behavior where

If apoc is installed using the one click installer buttons, other manually copied .jar plugins will not load.

if apoc is installed by copying it into the plugin folder, other manually copied .jar plugins will load.

**Comment by oskarhane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desktop plugin installer doesn't allow other plugins to register with the server](https://trello.com/c/D4JboWgR/386-desktop-plugin-installer-doesnt-allow-other-plugins-to-register-with-the-server)

**Comment by oskarhane** [comment]
Hi and thanks for the report.
This sure sounds like a bug. We'll get on it!

**Comment by BarsaTM** [comment]
Fixed.

Closing issue.
