### ISSUE TITLE
Neo4J Desktop database creation hangs on Windows 7

### ISSUE THREAD

**Issue by denisschlesinger** [neo4j-apps/neo4j-desktop#15]
Browser version: 1.0.22
DB version: 3.3.5
OS: Win7 64-bit

After upgrading to 1.0.22 Neo4j Desktop again hangs during creation of a new database (like it did in 1.0.15 and was described in https://github.com/neo4j-apps/neo4j-desktop/issues/9:

![image](https://user-images.githubusercontent.com/16976785/39044158-ac5dbf0a-448f-11e8-9c03-c6e73fe0386d.png)

**Comment by Metaur** [comment]
is this still an issue with latest Desktop version?

**Comment by denisschlesinger** [comment]
Hi!

No, the latest releases did not have that problem anymore! :)

Am Mi., 29. Aug. 2018 um 12:27 Uhr schrieb Sergey Kolunov <
notifications@github.com>:

**Comment by Metaur** [comment]
@denisschlesinger good to hear that!
