### ISSUE TITLE
Allow user to specify where Neo4j Desktop creates the ".Neo4jDesktop" folder

### ISSUE THREAD

**Issue by Caslon-Melior** [neo4j-apps/neo4j-desktop#17]
Each time that you start Neo4j Desktop, it creates the ".Neo4jDesktop" folder in your Windows user profile directory (if it does not already exist). The ".Neo4jDesktop" folder contains 343 MB of files. For users in a corporate environment where the user profile directory is mapped to a network server location, this can make it impossible to install Neo4j Desktop. In my case, the user profile is limited to 750 MB, of which 630 MB is used by current work project documents. The Neo4j 3.3 documentation does not seem to document whether there is a configuration setting for the default location of ".Neo4jDesktop" folder.

**Comment by BarsaTM** [comment]
Thank you for a feedback! 

This issue is fixed in version 1.1.3 and above.
