### ISSUE TITLE
Editing Graph remote connection lists password in clear text

### ISSUE THREAD

**Issue by mattcasters** [neo4j-apps/neo4j-desktop#19]
Running on Linux I'm running the desktop app in a terminal (neo4j-desktop-offline-1.1.5-x86_64.AppImage) and when I had trouble connecting to my local Neo4j instance I edited the Graph connection.
Looking through the log to see what was going on I noticed that the app lists the password in clear text.  I think this is not a good idea.

Log example:

[09:43:53:0634] [debug] Sending { createdAt: '2018-06-12T13:43:17.589Z',
  description: '',
  edit: false,
  encrypted: false,
  host: 'localhost',
  id: 'database-e7825854-4cd9-4900-af42-e60d6b2a6e6d',
  isPortValid: true,
  name: 'Local Neo4j Enterprise Edition',
  password: '3oim7%LfM3%7',
  port: 7687,
  projectId: 'project-e5c6c761-984f-44b3-8819-7ef6b2669a90',
  remoteConfiguration: 
   { protocols: { bolt: [Object], http: [Object], https: [Object] } },
  status: 'DEACTIVATED',
  step: 2,
  type: 'REMOTE_CONNECTION_UPDATED',
  username: 'matt' } null {}

**Comment by oskarhane** [comment]
Thanks for the report @mattcasters. This is definitely not a good idea.
We'll look into this straight away.

**Comment by oskarhane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Editing Graph remote connection lists password in clear text](https://trello.com/c/psAdibyd/491-editing-graph-remote-connection-lists-password-in-clear-text)

**Comment by BarsaTM** [comment]
[Fixed](https://github.com/neo-technology/neo4j-desktop/pull/367).

Closing issue.
