### ISSUE TITLE
Set location of databases

### ISSUE THREAD

**Issue by mfkilgore** [neo4j-apps/neo4j-desktop#2]
I would like the option to choose where to store the databases on my machine.  Right now I cannot see how to make this change.  In my case I have a 2nd drive with more space available.  

Thanks,

**Comment by buchgeher** [comment]
I would like to have this option too. Just switched from the community edition to the new "neo4j desktop" and I have absolutely no clue how I can open an already existing database located on another drive :-(

**Comment by mfkilgore** [comment]
@cybersam The desktop assumes the database name is a path under the data folder, so that will not help set a new location.  What we really need is the option to set a default drive/location during installation and/or the the ability to change that location.

**Comment by oskarhane** [comment]
This would indeed be a good feature! It's on our roadmap.

**Comment by Metaur** [comment]
This feature is implemented starting with 1.0.19
