### ISSUE TITLE
Unable to connect to remote database I get a meaningless error message

### ISSUE THREAD

**Issue by mattcasters** [neo4j-apps/neo4j-desktop#20]
Simply connecting to a local database ( bolt://matt@localhost:7687 ) fails to connect with:

Unable to establish remote connection: Error: Unknown or unsupported transport “disabled” for address “disabled:”

I made sure that remote connections in neo4j.conf are enabled and I managed to connect to bolt with other application.

**Comment by oskarhane** [comment]
Do you use the driver directly to try to connect, or neo4j-browser?
Why do you have a `matt@` in the bolt url?

**Comment by mattcasters** [comment]
In a project I clicked on "New Graph".
Result is the same with bolt://neo4j@localhost:7687

BUT I have generated passwords so I will try to simplify.

**Comment by mattcasters** [comment]
I tried to simplify by changing the password to abcd (perhaps it was an URL encoding issue or something like that) but to no avail.  Still get the same error.
Let me know if you want me to check anything else.

**Comment by Metaur** [comment]
@mattcasters Which OS are you using?

**Comment by Metaur** [comment]
@mattcasters ping

**Comment by mattcasters** [comment]
I'm on Linux (now Ubuntu 18.04.2 LTS) but fortunately the problem disappeared when I tried desktop .12

**Comment by Metaur** [comment]
@mattcasters thank you for the response. Will close the issue
