### ISSUE TITLE
Graphs Comparison

### ISSUE THREAD

**Issue by ddsaid** [neo4j-apps/neo4j-desktop#22]
Hi, 
I'm working on a project that turns around making a  neo4j DB for modeling the physical inventory of an ip/mpls network. My question is: how can i compare or see differences between to distinct graphs ? is there some tools ? or some functionnalities i neo4j?that can do this?  
Regards

**Comment by pe4cey** [comment]
Hi @ddsaid,

There is nothing built in to neo4j-desktop specifically for doing this.

I recommend heading over to the neo4j-users slack group (http://neo4j-users-slack-invite.herokuapp.com/). It's the best place to find answers to your questions.

Thanks

**Comment by ddsaid** [comment]
hi @pe4cey
