### ISSUE TITLE
Open an application from another application

### ISSUE THREAD

**Issue by nossila** [neo4j-apps/neo4j-desktop#24]
I'm building an application for Neo4j Desktop and I want to open Neo4j Browser app from my app, for example play a GraphGist as a browser guide. Is it possible?

**Comment by Metaur** [comment]
@nossila Good news, the feature you have requested, has been done. The infrastructure for such intercommunication for graph apps will be released soon (in Neo4j Desktop 1.1.13). Another thing to wait for would be the release of Neo4j Browser to support the newest changes.


Thanks for your patience.
