### ISSUE TITLE
Initialization Error - Unable to open Neo4j Desktop

### ISSUE THREAD

**Issue by jexp** [neo4j-apps/neo4j-desktop#28]
https://community.neo4j.com/t/initialization-error-unable-to-open-neo4j-desktop/806

**Comment by Metaur** [comment]
@jexp Seems like the neo4j-browser does not get downloaded to do an update. Not really sure why, maybe some kind of network issue.

As a workaround, I would suggest disabling the network for the app init phase. all the offline-bundled resources should be installed with no problem in that case.
