### ISSUE TITLE
Can't see UI

### ISSUE THREAD

**Issue by whatSocks** [neo4j-apps/neo4j-desktop#32]
Using Mac High Sierra 

[log.log](https://github.com/neo4j-apps/neo4j-desktop/files/2440326/log.log)

**Comment by Metaur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Offline resources are not copied due to a race condition](https://trello.com/c/REh06z2I/680-offline-resources-are-not-copied-due-to-a-race-condition)
