### ISSUE TITLE
Database failed to restart: DB [database-f6b0d9de-9954-4197-955c-ceb200b57d92] 'v3.4.7' exited with status 'KILLED'

### ISSUE THREAD

**Issue by mxbhatia** [neo4j-apps/neo4j-desktop#33]
Hello Neo4J Conmmunity,

Getting above error after terminating the session due to long running query.

Please help to resolve it. I am using Neo4j Desktop on Windows 10 machine

Thanks,
Mahesh

**Comment by Metaur** [comment]
@mxbhatia Could you please provide the steps to reproduce the issue?

**Comment by mxbhatia** [comment]
@Metaur Here is what I was trying to do:
1) LOAD approx 500K records from a CSV file (filesize: 140MB), the process errored out after running  for 15 mins - The LOAD CSV command is followed by a series of MERGE statements and one of the MERGE failed as it encountered null (or blank value ) in one of the CSV columns being loaded
2) Since the load was not successful and clean I tried deleting all Nodes and Relations using
MATCH (n)
DETACH DELETE n
the session again was running forever, I closed the Neo4j Browser and then tried to restart the server, this is when I am getting the error and its unable to restart now.

Thanks,
Mahesh

**Comment by mxbhatia** [comment]
Also my Windows 10 laptop has 8GB RAM and I am using Neo4j Desktop edition, pls suggest which configuration parameters viz  Pagesize, Heapsize etc. should be optimized and with what value  for my Neo4J database to improve the performance of LOAD--MERGE  and MATCH queries,  for this  volume of data (upto 1 million rows in CSV converting into 5-6 mutually related nodes in Neo4j?
Thanks

**Comment by oskarhane** [comment]
Hi @mxbhatia! Thanks for this issue. This is however not related to the application Neo4j Desktop.
Please seek guidance in https://community.neo4j.com to get answers to your questions for the Neo4j database.
