### ISSUE TITLE
graph stats not updated after importing data using ETL tool

### ISSUE THREAD

**Issue by whatSocks** [neo4j-apps/neo4j-desktop#34]
Mac OS High Sierra

* import some data using the ETL tool
* see data in the database browser
* don't see status updated on Neo4j Desktop

<img width="475" alt="screen shot 2018-10-14 at 6 18 38 pm" src="https://user-images.githubusercontent.com/2731744/46922913-e87c9180-cfdd-11e8-83e4-964977ac253e.png">

**Comment by Metaur** [comment]
@whatSocks this issue should be fixed in 1,1,12 version. Please try that
