### ISSUE TITLE
linkedin oauth failed - and neo4j deinstall does not cleanup all

### ISSUE THREAD

**Issue by kdwykleingeld** [neo4j-apps/neo4j-desktop#35]
During install of desktop 1.1.10 i noticed that the "linkedin" federated oauth authentication method did not work. Nothing happend and i only saw a blank screen. Using the GitHub based oauth method worked fine. Something to test maybe.

BTW.. the upgrade process to 3.4.9 resulted in teh fact that i could not start the database anymore and had to de-install the desktop and reinstall it after which i was able again restart my graph again. This only worked after i manually deleted several neo4j related (hidden) .desktop kind of folders. I suggest that the deinstall process will be extended to clean-up up everything

Running on w7.

thanks koen

**Comment by Metaur** [comment]
@kdwykleingeld Thanks for the report! Sorry for this late response, the next Desktop update will have the functionality to backup and remove the hidden data files. 
Ping me if you experience any issue with that
