### ISSUE TITLE
Windows Install - Java update failure

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-apps/neo4j-desktop#4]
Hi

When installing in Windows for some machines, the database fails to start due to a failed Java version update.

```
Database failed to start: DB [database-487df36b-8caa-4f22-b2d4-3312f41be1ac] 'v3.3.1' exited with status 'KILLED'. Check the logs
```
Workaround:

1.  Delete everything in C:\Users\[USERNAME]\AppData\Roaming\Neo4j Desktop\Application\distributions\java

2. Open Neo4j Desktop without authenticating

3. The correct version of Java will download and install

Test:
Create a new project and new local database, will start without errors

Proposed fix:
Test for presence of existing java and execute clean upgrade, perhaps include a user alert ("Upgrade java version to 1.8?"

**Comment by oskarhane** [comment]
This should be fixed in version 1.0.9, released yesterday.
