### ISSUE TITLE
Neo.ClientError.Statement.SyntaxError

### ISSUE THREAD

**Issue by kamilaMO** [neo4j-apps/neo4j-desktop#41]
Neo.ClientError.Statement.SyntaxError: Unknown function 'algo.getNodeById'
version 3.5.0 with graph-algorithms-algo-3.3.5.0.jar

**Comment by Metaur** [comment]
@kamilaMO I think this a good question for [this repository](https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues). 
Also could be more specific on the steps you made in Desktop to achieve this error?

**Comment by Metaur** [comment]
seems like a duplicate https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/786
