### ISSUE TITLE
Unable to Install Neo4J desktop on mac - Window for first time login unreadable

### ISSUE THREAD

**Issue by mbolner** [neo4j-apps/neo4j-desktop#45]
I have tried several times to set up the Neo4J desktop version on my Mac (OS X Yosemite, year 2015). I download the program and drag it into applications. When I try to open it, the window pops up as horizontal black and blue lines (See picture). I am unable to plug in the generic first time user username and password. I am only now starting to take courses on Computer Science, so I am not very tech savvy. Please let me know what steps I need to take to resolve this problem
<img width="1440" alt="screen shot 2019-01-31 at 21 25 29" src="https://user-images.githubusercontent.com/47150852/52171254-b7a89f80-2727-11e9-979d-53c9de060de1.png">

**Comment by Metaur** [comment]
@mbolner please start Desktop from the command line with a flag `--disable-gpu`. This is a known workaround for this particular problem. 

But the best solution here would be upgrading your MacOS, as Yosemite is a minimum supported version which has multiple known issues with electron apps and chromium.
