### ISSUE TITLE
Neo4j Desktop 1.1.15 installs OK but will not start on Windows 7 Ultimate N SP1

### ISSUE THREAD

**Issue by ma2ts** [neo4j-apps/neo4j-desktop#49]
Environment: Windows 7 Ultimate N SP1
Running JDK 11.0.1 64 bit

Have been happily running Neo4j Desktop 1.1.10 (with its various updates) since October 2018. Using the single user install.

Updated today through the Neo4j Desktop GUI to version 1.1.15 and now Neo4j Desktop will not launch at all. Or to be more precise, the "Neo4j Desktop.exe" process(es) do start (2 are listed in Task Manager, one using c.82K memory, one using c.5K memory) but the GUI itself simply does not appear.

Tried rebooting PC (made no difference). Tried fully uninstalling and then re-installing 1.1.15 (still no difference).

**Comment by Metaur** [comment]
@ma2ts Could you please share the info on what version of Powershell you are using? Also, it would be useful to know what script execution policy you have set on your system.

**Comment by ma2ts** [comment]
@Metaur PS version is 2 and policy is Restricted.

For info, I've reverted to Neo4j Desktop 1.1.10 (from original installation download) and everything is OK again with that version.

**Comment by Metaur** [comment]
@ma2ts this issue should be fixed in the next release (the one that will come after 1.1.17) in about a month.
Please stay tuned. Also, I could ping you when we will have the fix available in the Canary build to get your feedback on the fix.

**Comment by ma2ts** [comment]
@Metaur Thanks, that is good to know! I'll look forward to the fix.

**Comment by gotthub** [comment]
I am having the same issue on Windows 7 Enterprise running Java 8 Update 161 also Powershell 2 policy is RemoteSigned.
Tried installing/unsinstalling several times in different folders. In the end I am always stuck with 2 running processes and no GUI. Any suggestions? I have no installer for former versions as I am new to Neo4j.

Thanks!

**Comment by Metaur** [comment]
@ma2ts @gotthub 
You can now download a Canary build from [here](https://neo4j.com/download-center/#releases), in the `Neo4j Desktop` tab `Pre-releases` section.

Once you try the build, please share any observations. Thank you.

**Comment by gotthub** [comment]
Thank you @Metaur!
Same issue with 1.1.18-dev.0 (exe) though, but now have this entry in log.log:
(...)
[2019-03-05 16:34:59:0063] [info] Creating new client ID
[2019-03-05 16:35:32:0374] [error] Protocol Manager type error: url must be string. url = undefined
[2019-03-05 16:37:10:0451] [info] App starting
(...)

**Comment by ma2ts** [comment]
I just had a look at my backup of log.log (from when I was trying to run 1.1.15).

It also contained multiple instances of the same error as gotthub above:
[error] Protocol Manager type error: url must be string. url = undefined

Plus also two separate warnings relating to powershell command failures:
[...] Get-AuthenticodeSignature [...]
and
[...] $ExecutionContext.SessionState.LanguageMode [...]

**Comment by Metaur** [comment]
@gotthub @ma2ts please kill the Neo4j Desktop processes in the task manager and try running Desktop once again (the canary one). If that fails, it would be really helpful to get the whole log file, so that this issue could be investigated more deeply.

**Comment by gotthub** [comment]
@Metaur I did just that a few times, the behavior is somewhat not the same. Sometimes there is an error in the log, sometimes not. Sometimes it just one process, mostly two. I saw a third one popping up in task manager for a second. Either or the UI is not showing. 
Are there other file or system locations where one could look for events/errors? Also I could not find out if the JVM has been installed as well and where.
[log.log](https://github.com/neo4j-apps/neo4j-desktop/files/2936035/log.log)

**Comment by Metaur** [comment]
@gotthub at this point you should not worry about jvm. It will be installed after you see the UI (in case of non-offline build). 

You could try removing the Desktop data folder (for Canary it is `%APPDATA%\Neo4j Desktop Canary\Application`), killing zombie Desktop processes and start again.

**Comment by gotthub** [comment]
@Metaur did as you suggested but that didn't change much. The error does not show up in the log anymore but still no GUI or other hint to the problem.
[log.log](https://github.com/neo4j-apps/neo4j-desktop/files/2938562/log.log)

**Comment by ilyin371** [comment]
Well, another option is to upgrade PowerShell to version 5 (at least) and try a regular Neo4j Desktop 1.1.17 build again.

Mysterious that the pre-release build gets stuck without any clues in log file.

**Comment by akollegger** [comment]
Closing this as it concerns an older release of Neo4j Desktop. Please re-open if similar behaviours or problems occur in the latest release, Neo4j Desktop 1.3.4.

**Comment by nitinsinhaa** [comment]
I have installed the neo4j desktop 1.5.8.
After installing, the application is not opening.
I am using Windows 11

Error in the log: 
Protocol Manager type error: url must be string. url = undefined

[log.log](https://github.com/neo4j-devtools/neo4j-desktop/files/11995044/log.log)
