### ISSUE TITLE
Database failed to create: Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by MichaelRBlack** [neo4j-apps/neo4j-desktop#50]
I'm trying to create a new local graph and I'm getting the following error:

`Database failed to create: Error: EISDIR: illegal operation on a directory, open 'C:\Users\mblack\.Neo4jDesktop\neo4jDatabases\database-2c261a08-97b8-4798-a04d-7a7b5c028c84\installation-3.5.3\data'`

I'm trying to install the latest version 3.5.3 which I have never done before, but I have found that I can create a v3.5.2 graph because I assume it's the version Neo4j Desktop came shipped with.

I've tried uninstalling Neo4j Desktop, deleting and Neo4j files on my computer that I could find, reinstalling desktop but the problem persists.

**Comment by MichaelRBlack** [comment]
I just tried this on a different computer and observed the same bug.

**Comment by kdwykleingeld** [comment]
i have exactly the same error upgrading from 3.5.2. to .3.5.3
Failed to upgrade database: Error: EISDIR: illegal operation on a directory, open 'C:\Users\.Neo4jDesktop\neo4jDatabases\database-ffca7d5a-b65a-45b9-ab6d-3c15cc302390\installation-3.5.3\data'

I tried it with and without a database with same result.. i did not check the auto migrate database option and my conf file allows auto upgrad from prev versions ..

Any clues 

Thanks Koen

**Comment by kdwykleingeld** [comment]
Or is this not the correct place to report issues ?  Where to report ?? I do not see much replies on most issues .. reg koen

**Comment by Metaur** [comment]
@MichaelRBlack the neo4j of 3.5.3 has some issues on Windows, We have implemented a fix for that in Neo4j Desktop, which will roll out somewhere around next week. Please use a different neo4j version for now. Once you'll get the Desktop update - this issue will be fixed.

**Comment by Metaur** [comment]
@kdwykleingeld Yes, this is the right place to report issues :) We are really sorry that we reply to your questions not too often. We will do our best.

In case if there is a super urgent issue - you could also use the [community portal](https://community.neo4j.com/) or get in touch with the development or support team in [slack](https://neo4j-users-slack-invite.herokuapp.com/)

**Comment by kdwykleingeld** [comment]
Hi , thanks, no hurry for me i will just wait till new desktop version is available before i will retry the upgrade. Thanks Regards Koen

**Comment by kdwykleingeld** [comment]
thanks, just installed the latest version of the desktop and upgraded smoothly to 3.5.3. reg koen
