### ISSUE TITLE
Error "Cannot load license" in mac

### ISSUE THREAD

**Issue by vinitpayal** [neo4j-apps/neo4j-desktop#51]
While installing the latest version(1.1.15) of the neo4j desktop on mac we are getting "Cannot load license" and nothing happens from there.

Please note that earlier version of it was working perfectly fine.

Please refer screenshot below:-
[error screenshot](https://discourse-cdn-sjc1.com/business4/uploads/neo4jcommunity/original/2X/0/0f28d87eb887e3ff1f7caa2e66f03e0645b1e40e.png)

**Comment by Metaur** [comment]
@vinitpayal please check the contents of `~/Library/Application Support/Neo4j Desktop/Application/persist/licenses.json` file. Seems like something has gone wrong and the incorrect activation key has been written there. 

Which activation keys you were using in Desktop (eg. for Desktop, Neo4j Bloom, etc.)?

**Comment by vinitpayal** [comment]
Thanks @Metaur yes looks like that was the issue just cleared ~/Library/Application Support/Neo4j Desktop and reinitialized and it started up.

But now facing a new issue my credentials which is working from my code script and even working from neo4j provided UI on 7474 port but in neo4j desktop giving **username or passphrase you entered is not correct.** error which is really weird.

**Comment by Metaur** [comment]
@vinitpayal Does your passphrase contain any special characters?
Could you check the log file for any clues around this issue? The path to the log file is `~/Library/Logs/Neo4j Desktop/log.log`

**Comment by vinitpayal** [comment]
Yes @Metaur I do have special characters in my passphrase. 

Last log in above file is 
`[2019-03-04 16:47:37.710] [error] Unable to establish remote connection Error: The username or passphrase you entered is not correct.
[2019-03-04 16:47:55.471] [info] App is quitting
[2019-03-04 16:47:55.489] [info] Closing PouchDB[projects].
[2019-03-04 16:47:55.490] [info] Closing PouchDB[databases].
[2019-03-04 16:47:55.491] [info] Closing PouchDB[userData].
[2019-03-04 16:47:55.491] [info] Closing PouchDB[plugins].
[2019-03-04 16:47:55.491] [info] Closing PouchDB[distributions].
[2019-03-04 16:47:55.491] [info] Closing PouchDB[graphApps].
[2019-03-04 16:47:55.492] [info] Closing PouchDB[licenses].
[2019-03-04 16:47:55.519] [info] App quit with 0 code`

But no logs are getting generated when am trying to connect now.

**Comment by vinitpayal** [comment]
Also tried changing passphrase without any special character still doesn't work. 

It says **Unable to establish remote connection: Error: The username or passphrase you entered is not correct.**

Also am attaching the screenshot of developer console.

![image](https://user-images.githubusercontent.com/10959000/53732755-e5a70e00-3ea4-11e9-92e4-29828d7a5919.png)

**Comment by Metaur** [comment]
@vinitpayal First of all please check that the connection url is a correct bolt endpoint. Also, check the username used for the remote connection and the encryption presence for your connection.

**Comment by vinitpayal** [comment]
Yes @Metaur checked multiple times, there isn't any problem with it as am just copy pasting same things in neo4j UI in browser parallel and over there it's working perfectly fine.

**Comment by Metaur** [comment]
@vinitpayal Do you have any special settings for your neo4j instance that we should be aware of? I would like to reproduce this issue locally

**Comment by vinitpayal** [comment]
Thanks @Metaur for being so responsive, I think below details should come handy:-
1) user name is an email address 
2) password have tried both with special characters and without special character so shouldn't matter
3) Neo4j is hosted using docker image provided by neo4j team(Version: 3.5.3) 
4) Have registered for neo4j desktop using google login which gives licence to use it for 1 year I guess.
5) Neo4j desktop version have tried(1.1.15 & 1.1.17) and facing same issues in both

Also we are having 2-3 neo4j instances running all using same docker image and it's giving same error to all of them also all of them are getting connected successfully using neo4j provided inbuilt UI with same credentials.

Please let me know if can provide any other info which can help.

**Comment by Metaur** [comment]
@vinitpayal tried to start a local neo4j instance. Connected successfully, even is the password contained special characters. 
Which Neo4j Browser you are using for testing? The one available at `localhost:7474`? Is your Neo4j instance exposed to the outer world within docker? can you ping the `7687` port?

**Comment by vinitpayal** [comment]
Hey @Metaur Thank you so much for being so proactive in responding, it's very weird that it wasn't working from my office but when I tried same thing from my home wi-fi it worked.

And yes our instance is exposed to outer world which also gets proved because we are able to connect to it with our script which is running in GAE(google app engine) and we don't have any ip filtering for port 7687.

Sorry for all the troubles @Metaur, Closing this issue for now as it's working fine.
