### ISSUE TITLE
Long logs cause db shutdown

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-apps/neo4j-desktop#6]
Hi,

Certain procedures (eg graphaware nlp, neosemantics) have verbose logging.

After several hundred entries, Neo4j desktop will crash.

Should be a switch to start up in console mode or service mode, or offer automatic console truncation.

Thanks,

Michael

**Comment by oskarhane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Long logs cause db shutdown](https://trello.com/c/zD8dMDEB/310-long-logs-cause-db-shutdown)

**Comment by Metaur** [comment]
@graphadvantage Hi, Could you please check the fix for your issue in the latest 1.1.9 release?
