### ISSUE TITLE
Neo4j Desktop online Graph App icon not right when restart the Neo4j Desktop.

### ISSUE THREAD

**Issue by lixuanxian** [neo4j-apps/neo4j-desktop#63]
Ne4j Desktop Online Graph App icon issues repeat steps, refer the repo <https://github.com/Kineviz/neo4jDesktopIconIssues>

1. Install Graph Application (ICON DEMO)
Please use http://neo4jdesktopiconissues.code4demo.com/ as Graph App URL, then add app ICON DEMO Your will see right icon. 
![](http://neo4jdesktopiconissues.code4demo.com//issues/install-right.png)

2. Restart the Neo4j Desktop app. You will see the icon is not right now.
Please restart neo4j desktop app, your the ICON DEMO's icon change to neo4j default Graph App icon 

![](http://neo4jdesktopiconissues.code4demo.com/issues/restart-failed.png)

**Comment by oskarhane** [comment]
Thanks for the report @lixuanxian!
We'll have a look at it.

**Comment by oskarhane** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Neo4j Desktop online Graph App icon not right when restart the Neo4j Desktop](https://trello.com/c/tnPi8B93/942-neo4j-desktop-online-graph-app-icon-not-right-when-restart-the-neo4j-desktop)

**Comment by oskarhane** [comment]
This is now fixed and will be in next release. Thanks for reporting @lixuanxian.
