### ISSUE TITLE
can't uninstall Neo4j Desktop (community) from Ubuntu 19.04

### ISSUE THREAD

**Issue by invisiblegaudi** [neo4j-apps/neo4j-desktop#77]
I've tried apt-get but it just tells me neo4j-client isn't installed.

**Comment by nglgzz** [comment]
What command did you use to install Neo4j Desktop?

**Comment by invisiblegaudi** [comment]
I'm pretty sure I downloaded and installed via the website!

John
---
Let's make this conversation private!
Get your own free encrypted mailbox
https://tutanota.com





14 Feb 2020, 09:53 by notifications@github.com:

**Comment by invisiblegaudi** [comment]
I still have it in my applications menu but i had to delete ./config/Neo4j Desktop

John
---
Let's make this conversation private!
Get your own free encrypted mailbox
https://tutanota.com





14 Feb 2020, 09:53 by notifications@github.com:

**Comment by nglgzz** [comment]
If you downloaded the [AppImage](https://neo4j.com/download-center/#desktop), to uninstall you need to remove the following items: 

- The downloaded AppImage: this is the executable used to run Neo4j Desktop.
- The `~/.config/Neo4j Desktop` directory: this is where Neo4j Desktop stores configuration files, databases, apps, plugins, and some other files. 
- The `~/.local/share/applications/appimagekit-neo4j-desktop-[version].AppImage` file: this is a [*.desktop entry](https://wiki.archlinux.org/index.php/Desktop_entries#Tools), a file used by most [desktop environments](https://wiki.archlinux.org/index.php/Desktop_environment) to list installed applications. To refresh the content of your application menu after deleting or making changes to this *.desktop entries you can run `sudo update-desktop-database` (this is a system command, it's unrelated to Neo4j Desktop) or reboot.

Let me know if that helps.
