### ISSUE TITLE
Neo4j Desktop - Frequent JS errors

### ISSUE THREAD

**Issue by luanne** [neo4j-apps/neo4j-desktop#82]
JS errors (see attached screenshot) pop up very frequently

**Neo4j Desktop Version**: 1.2.7 (1.2.7.1676)
**Operating System**: MacOS Mohave

**Steps to reproduce**

Open Neo4j Desktop
Perform usual operations- start a database, use the browser etc.

**Expected behavior**
No errors pop up

**Actual behavior**
The following error frequently pops up
![image](https://user-images.githubusercontent.com/1242476/80864625-e26c0580-8c94-11ea-930d-b4afac6d0d0b.png)

**Comment by akollegger** [comment]
@luanne Are you still seeing these exceptions popping up?

**Comment by luanne** [comment]
Hi Andreas, yes I am

**Comment by luanne** [comment]
They have gone away with the latest(?) version 🎉
