### ISSUE TITLE
Exception is thrown in KDE distribution Kubuntu OS

### ISSUE THREAD

**Issue by aaramg** [neo4j-apps/neo4j-desktop#83]
![image](https://user-images.githubusercontent.com/20701693/80867839-60390c80-8ca7-11ea-9e2c-0c115b873e03.png)
I cannot start the desktop program. I have tried it in Ubuntu before and it was working. But don't know why it throws exceptions in Kubuntu. Maybe there is some conflict with KDE Plasma?
Please test it in one of the KDE distributions.
Here is my system info:
![image](https://user-images.githubusercontent.com/20701693/80868081-50bac300-8ca9-11ea-9098-4a14b3486339.png)

**Comment by aaramg** [comment]
I found the solution.
`sudo apt install keyutils`
This resolved the issue. But I guess this should be tested and somehow included or documented. I guess normal Ubuntu has this by default. So maybe during the tests, this issue was not triggered.

**Comment by nglgzz** [comment]
Thank you for your report @aaramg. 

Neo4j Desktop uses gnome-keyring as the default keyring in Linux, and it falls back to the keyctl utility when gnome-keyring is not available. Keyctl is built into the Linux kernel, so I'm not sure why it's not available by default in Kubuntu. 

I will add this to the docs in case someone else comes across this issue. Thank you for sharing your solution.

**Comment by nglgzz** [comment]
I added this case to the troubleshooting section, you can see it here: https://github.com/neo4j-apps/neo4j-desktop/wiki/Troubleshooting-(Linux)#solution-2
