### ISSUE TITLE
creating a new DB fails after update from 1.0.14 to 1.0.15

### ISSUE THREAD

**Issue by rescuehero** [neo4j-apps/neo4j-desktop#9]
I found out, that on the new Desktop version the Database creating does not work for me.

- Neo4j Desktop Version: 1.0.15
- Neo4j version: 3.3.3 CE
- Operating system: Win7, Win10
- Steps to reproduce : Upgrade from desktop version 1.0.14 to Desktop version 1.0.15
- Expected behavior: creating a new database works flawless in a few seconds
- Actual behavior: creates the folder of the database in neo4j path, but the client keeps loading and loading
![grafik](https://user-images.githubusercontent.com/11653204/36483101-82121bf8-1715-11e8-88de-2a3e4d2fbd4d.png)

If you need some more information, i am going to share it as fast as i can.

**Comment by Metaur** [comment]
@rescuehero Do you have any system pop ups during database creation (asking for password)? We now use system secure keychain for storing passwords

**Comment by rescuehero** [comment]
steps to reproduce:
open neo4j desktop
open a project
click on new graph, enter Name and password in given Boxes, choose 3.3.3 (latest)
click create
"creating a new database..."

no pop up or something to enter password

should i go and try on a win10 system?

**Comment by Metaur** [comment]
@rescuehero does your win7 installation includes a credential vault program (or credential manager)?

**Comment by rescuehero** [comment]
Pictures of credential manager below. Let me know if you need a translation for something.

![credentialmanager](https://user-images.githubusercontent.com/11653204/36537727-49b65a5a-17d1-11e8-9be3-72e1f8b575e0.png)
![credentialmanager2](https://user-images.githubusercontent.com/11653204/36537728-49d7fc0a-17d1-11e8-87f8-7d56425a3207.png)
![grafik](https://user-images.githubusercontent.com/11653204/36537839-9d29c5f0-17d1-11e8-84f0-a7979e0e3df2.png)

**Comment by rescuehero** [comment]
I deleted the entries and reopened a old DB:
after entering cypher:DB connect and connecting to db, i looked in neo4j which showed this:
![grafik](https://user-images.githubusercontent.com/11653204/36539225-57f93d76-17d6-11e8-9388-8a1e764d47ac.png)
and then created a new entry in the credential manager.

creating a new database still does not work. No entry is added to the credential manager, even though a folder in explorer gets created. There are 5 folders now, but after restarting Neo4j Desktop, only one shows up. The one I created in 1.0.14

Running Neo4j Desktop with admin privileges did not solve the problem.

**Comment by rescuehero** [comment]
even with newest version it is not working.

**Comment by noshankus** [comment]
I also have this behavior on Windows 7 with the latest Neo4j 1.0.17.
First time installer, all goes well until creating a database - it downloads the software, then tries "Creating a new database..." - but never ends.

In the logs, I have a single warning:
`[2018-03-08 10:59:19:0453] [warn] auth is not initialised yet`

I don't see anything neo4j related in the "Credential Manager".

**Comment by noshankus** [comment]
So, the 1.0.14 version does indeed work as expected.
Likely the issue is as described above, no pop-up for the "system secure keychain".

**Comment by rescuehero** [comment]
is fixed in newest version for me
